### ISSUE TITLE
WorkflowError: The singularity command has to be available in order to use singularity integration.

### ISSUE THREAD

**Issue by pillepalle123** [kentsisresearchgroup/UltraQuant#4]
Hi, thanks a lot for providing this!
Unfortunately, I am getting an error. Does someone have an idea what the cause could be?

File in work directory:
`Building DAG of jobs...
WorkflowError:
The singularity command has to be available in order to use singularity integration.`

..has been solved

**Comment by sentisci** [comment]
How did you resolve this issue?
